# boot_jtag.tcl - Volatile JTAG boot for blank PL+PS
#
# Uses psu_init.tcl (generated by Vivado) to initialize PS registers
# directly via JTAG, bypassing the FSBL. This is the most reliable
# approach for a blank-boot scenario.
#
# Order:
#   1. System reset APU (clean PS state)
#   2. Run psu_init via JTAG (PLL, DDR, clocks, MIO, peripherals)
#   3. Run psu_post_config and psu_ps_pl_reset_config
#   4. Program bitstream (PL starts fresh with PS already initialized)
#   5. Test ready
connect -url tcp:localhost:3121

set bit_file     "./pl_ps_ddr_mem_test_proj/pl_ps_ddr_mem_test.runs/impl_1/system_wrapper.bit"
set psu_init_tcl "./psu_init.tcl"

if {![file exists $bit_file]}     { puts "ERROR: bitstream not found"; exit 1 }
if {![file exists $psu_init_tcl]} { puts "ERROR: psu_init.tcl not found"; exit 1 }

# --- Step 1: System reset APU ---
puts "Step 1: System reset APU..."
targets 8
rst -system
puts "APU system reset done."

# --- Step 2: Initialize PS via psu_init.tcl ---
puts "Step 2: Sourcing psu_init.tcl..."
targets 4

# Define mask_write (not in psu_init.tcl, but used by its data blocks).
# Uses same parsing approach as psu_init.tcl's psu_mask_write.
proc mask_write { addr mask value } {
    set curval "0x[string range [mrd -force $addr] end-8 end]"
    set curval [expr {$curval & ~($mask)}]
    set maskedval [expr {$value & $mask}]
    set maskedval [expr {$curval | $maskedval}]
    mwr -force $addr $maskedval
}

# Source psu_init.tcl - this defines psu_init, psu_post_config,
# psu_ps_pl_reset_config, psu_ps_pl_isolation_removal, psu_mask_write,
# mask_read, mask_poll, poll, init_serdes, init_peripheral, etc.
source $psu_init_tcl

puts "Running psu_init..."
psu_init
puts "psu_init done."

puts "Running psu_post_config..."
if {[catch {psu_post_config} err]} {
    puts "psu_post_config: $err"
}

puts "Running psu_ps_pl_reset_config..."
if {[catch {psu_ps_pl_reset_config} err]} {
    puts "psu_ps_pl_reset_config: $err"
}

puts "Running psu_ps_pl_isolation_removal..."
if {[catch {psu_ps_pl_isolation_removal} err]} {
    puts "psu_ps_pl_isolation_removal: $err"
}

# --- Step 3: Verify DDR ---
puts "Verifying DDR..."
mwr -force 0x10000000 0xDEADBEEF
after 100
set val [mrd -force 0x10000000]
puts "DDR readback: $val"

# --- Step 4: Program bitstream ---
puts "Step 4: Programming bitstream..."
targets -set -nocase -filter {name =~ "PS TAP"}
fpga $bit_file
puts "Bitstream programmed. PL POR releases tester after ~5ms."
after 500

puts "Boot complete. PS DDR initialized, PL tester running."
puts "Now test: python host/pl_ps_ddr_test.py --port COM6 --query-map"
disconnect
